Vagrant.configure(2) do | config | 
    config.vm.box = "icloudnote/ubuntu"
    config.vm.network "public_network"

    config.vm.provider "virtualbox" do | vb |
        vb.name="javaserver"
        vb.memory=1024
        vb.cpus=2
        vb.gui=false
        vb.customize ["modifyvm", :id, "--cpu-execution-cap", "90"]
    end
end