Vagrant.configure(2) do | config |
    config.vm.box = "icloudnote/ubuntu"
    config.vm.network "forwarded_port", host: 8080, guest: 80

    config.vm.provider "virtualbox" do | vb |
        vb.name="apache2server"
        vb.cpus=2
        vb.memory=1024
    end
end