Vagrant.configure(2) do | config |
    config.vm.box = "icloudnote/ubuntu"

    config.vm.provider "virtualbox" do | vb |
        vb.name="inlineprov"
        vb.cpus=2
        vb.memory=1024
    end

    #config.vm.provision "install java", type: "shell", inline: "sudo apt update -y && sudo apt install -y openjdk-17-jdk"
    config.vm.provision "shell", inline: "sudo apt install net-tools"

end