Vagrant.configure(2) do | config |
    config.vm.box = "icloudnote/ubuntu"

    config.vm.provider "virtualbox" do | vb |
        vb.name="runwithprov"
        vb.cpus=2
        vb.memory=1024
    end

    config.vm.provision "install net-tools", type: "shell", inline: "sudo apt update -y && sudo apt install -y net-tools", run: "always"


end