Vagrant.configure(2) do | config |
    config.vm.box="icloudnote/ubuntu"

    config.vm.provider "virtualbox" do | vb | 
        vb.name="blockprov"
        vb.cpus=4
    end

    config.vm.provision "net-tools", type: "shell" do | prov |
        prov.inline="sudo apt update -y"
        prov.inline="sudo apt install -y net-tools"
    end
end