Vagrant.configure(2) do | config |
    config.vm.box = "icloudnote/ubuntu"
    config.vm.synced_folder "/Users/sriman/quickshare", "/extshare"

    #config.vm.network "private_network", type: "dhcp"
    #config.vm.network "private_network", ip: "172.1.10.21"
    config.vm.network "private_network", ip: "192.169.10.12" , virtualbox_intnet: "net1"
end