Vagrant.configure(2) do | config |
    config.vm.box="icloudnote/ubuntu"
    
    config.vm.network "public_network"
    #config.vm.network "public_network", ip: "192.168.1.10"
    #config.vm.network "public_network", ip: "192.168.1.10", bridge: ["en0"]
end
