Vagrant.configure(2) do | config | 

    config.vm.define "ng_dbserver" do | db | 
        db.vm.box = "icloudnote/ubuntu"
        db.vm.network "private_network", ip: "192.168.50.10", virtualbox_intnet: "ngconnectnw"

        db.vm.provider "virtualbox" do | dbvb |
            dbvb.name = "ng_dbserver"
            dbvb.cpus = 2
            dbvb.memory = 1024
        end
    end

    config.vm.define "ng_javaserver" do | java | 
        java.vm.box = "icloudnote/ubuntu"
        java.vm.network "private_network", ip: "192.168.50.11", virtualbox_intnet: "ngconnectnw"
        java.vm.network "forwarded_port", host: 8080, guest: 8080

        java.vm.provider "virtualbox" do | javavb |
            javavb.name = "ng_javaserver"
            javavb.cpus = 2
            javavb.memory = 1024
        end
    end
end