Vagrant.configure(2) do | config |
    #global configuration
    config.vm.provision "net-tools", type: "shell", inline: <<-SCRIPT
        sudo apt update -y
        sudo apt install -y net-tools
    SCRIPT

    #machine blocks
    config.vm.define "dbserver" do | dbserver |
        dbserver.vm.box = "icloudnote/ubuntu"
        dbserver.vm.network "private_network", ip: "192.168.20.10"

        dbserver.vm.provider "virtualbox" do | dbvb |
            dbvb.name = "dbserver"
            dbvb.cpus = 2
            dbvb.memory = 1024
        end
    end

    config.vm.define "appserver" do | appserver |
        appserver.vm.box = "icloudnote/ubuntu"
        appserver.vm.network "private_network", ip: "192.168.20.11"

        appserver.vm.provider "virtualbox" do | apvb |
            apvb.name="appserver"
            apvb.cpus = 2
            apvb.memory = 1024
        end
        appserver.vm.provision "jdk17", type: "shell", inline: "sudo apt install -y openjdk-17-jdk"
    end
end