Vagrant.configure(2) do | config |
    config.vm.box="icloudnote/ubuntu"

    config.vm.provider "virtualbox" do | vb | 
        vb.name="multilineprov"
        vb.cpus=4
    end

    config.vm.provision "net-tools", run: "always", type: "shell", inline: <<-SCRIPT
        sudo apt update -y
        sudo apt install -y net-tools
    SCRIPT
end